<?php
declare(strict_types=1);

// RepresentOfficials SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

RepresentOfficialsUtility::setRegistrar(function (RepresentOfficialsUtility $u): void {
    $u->clean = [RepresentOfficialsClean::class, 'call'];
    $u->done = [RepresentOfficialsDone::class, 'call'];
    $u->make_error = [RepresentOfficialsMakeError::class, 'call'];
    $u->feature_add = [RepresentOfficialsFeatureAdd::class, 'call'];
    $u->feature_hook = [RepresentOfficialsFeatureHook::class, 'call'];
    $u->feature_init = [RepresentOfficialsFeatureInit::class, 'call'];
    $u->fetcher = [RepresentOfficialsFetcher::class, 'call'];
    $u->make_fetch_def = [RepresentOfficialsMakeFetchDef::class, 'call'];
    $u->make_context = [RepresentOfficialsMakeContext::class, 'call'];
    $u->make_options = [RepresentOfficialsMakeOptions::class, 'call'];
    $u->make_request = [RepresentOfficialsMakeRequest::class, 'call'];
    $u->make_response = [RepresentOfficialsMakeResponse::class, 'call'];
    $u->make_result = [RepresentOfficialsMakeResult::class, 'call'];
    $u->make_point = [RepresentOfficialsMakePoint::class, 'call'];
    $u->make_spec = [RepresentOfficialsMakeSpec::class, 'call'];
    $u->make_url = [RepresentOfficialsMakeUrl::class, 'call'];
    $u->param = [RepresentOfficialsParam::class, 'call'];
    $u->prepare_auth = [RepresentOfficialsPrepareAuth::class, 'call'];
    $u->prepare_body = [RepresentOfficialsPrepareBody::class, 'call'];
    $u->prepare_headers = [RepresentOfficialsPrepareHeaders::class, 'call'];
    $u->prepare_method = [RepresentOfficialsPrepareMethod::class, 'call'];
    $u->prepare_params = [RepresentOfficialsPrepareParams::class, 'call'];
    $u->prepare_path = [RepresentOfficialsPreparePath::class, 'call'];
    $u->prepare_query = [RepresentOfficialsPrepareQuery::class, 'call'];
    $u->graphql_body = [RepresentOfficialsGraphql::class, 'body'];
    $u->graphql_errors = [RepresentOfficialsGraphql::class, 'errors'];
    $u->result_basic = [RepresentOfficialsResultBasic::class, 'call'];
    $u->result_body = [RepresentOfficialsResultBody::class, 'call'];
    $u->result_headers = [RepresentOfficialsResultHeaders::class, 'call'];
    $u->transform_request = [RepresentOfficialsTransformRequest::class, 'call'];
    $u->transform_response = [RepresentOfficialsTransformResponse::class, 'call'];
});
